---

# Delegate further configuration to subtasks
# placed in this same directory.

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: install.yml
- include: configure.yml

- name: Ensure supervisord is running
  become: yes
  service:
    name: "{{supervisord_service_name}}"
    state: running
    enabled: yes
  tags:
    - init
    - supervisor
    - supervisord
